# Generated by Django 2.1 on 2018-09-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время добавления', verbose_name='Время добавления')),
                ('name', models.CharField(help_text='Заголовок', max_length=250, verbose_name='Заголовок')),
                ('status', models.BooleanField(default=False, help_text='Статус активно/скрыто', verbose_name='Статус')),
                ('content', models.TextField(help_text='Содержимое', max_length=50000, verbose_name='Содержимое')),
                ('order', models.IntegerField(default=0, help_text='Сортировка', verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Содержимое',
                'verbose_name_plural': 'Содержимое',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время добавления', verbose_name='Время добавления')),
                ('name', models.CharField(help_text='Название страницы', max_length=150, verbose_name='Название страницы')),
                ('slug', models.CharField(blank=True, default=False, help_text='Url страницы', max_length=250, verbose_name='Url страницы')),
                ('status', models.BooleanField(default=False, help_text='Статус активна/скрыта', verbose_name='Статус')),
                ('title_tag', models.TextField(help_text='Тег Title', max_length=150, verbose_name='Тег Title')),
                ('meta_tag_description', models.TextField(help_text='Тег Description', max_length=300, verbose_name='Тег Description')),
                ('meta_tag_keywords', models.TextField(help_text='Тег Keywords', max_length=5000, verbose_name='Тег Keywords')),
                ('template', models.CharField(default='default', help_text='Название шаблона', max_length=30, verbose_name='Название шаблона')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(help_text='Страницы', on_delete=django.db.models.deletion.CASCADE, to='page.Page', verbose_name='Страницы'),
        ),
    ]
