# Generated by Django 2.1 on 2018-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(blank=True, help_text='Название шаблона', max_length=30, verbose_name='Название шаблона'),
        ),
    ]
