version: '3'

services:


  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver --settings core.settings.staging"
    working_dir: /opt/webapp/web
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/opt/webapp


  postgres:
    image: postgres:10
    env_file:
      - .env
    network_mode: host
    volumes:
      - postgres:/var/lib/pgsql/10/data/

  redis:
    image: redis


volumes:
  postgres:
    driver: local