version: '3'

services:

  web:
    command: .bin/run.sh staging
    ports:
      - 80:80
    environment:
      - SECRET_KEY=asdasd5!22434%66744dfsdfssdfs!s9ssdj
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432  
  postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    ports:
      - 5432:5432