# Generated by Django 2.2.3 on 2019-11-28 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='Менеджер', on_delete=django.db.models.deletion.CASCADE, related_name='manager', related_query_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='Агент', on_delete=django.db.models.deletion.CASCADE, related_name='agent', related_query_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
            ],
        ),
    ]
